### ISSUE TITLE
关键是稳不稳？有大型项目应用案例吗？

### ISSUE THREAD

**Issue by 1021683053** [shenjunru/react-fiber-keep-alive#4]
建议把原理附上，容易排查问题。

**Comment by shenjunru** [comment]
原理就好比把 dom 节点 detach 再 attach。
只不过是发生在 react 的 fiber tree 上。
因为涉及 react 的核心 fiber 的一整套逻辑。
详细的文档我还在构思要怎么写。也欢迎 PR。

欢迎尝试，遇到问题的话，可以提bug。（附上简单的demo更好）
如果达到预期，不就是项目案例了嘛。:p

**Comment by shenjunru** [comment]
稳定性可以先看你的代码在 react 的 strict mode 下是不是会有问题

**Comment by 1021683053** [comment]
> 欢迎尝试，遇到问题的话，可以提bug。（附上简单的demo更好）
> 如果达到预期，不就是项目案例了嘛。:p

万一耽误工期，被骂我这得自己兜着呀🤥。

**Comment by shenjunru** [comment]
花一分钟加几行代码，如果达不到预期，撤销一下即可
