### ISSUE TITLE
Can i use it with any renderer?

### ISSUE THREAD

**Issue by dungeon2567** [shenjunru/react-fiber-keep-alive#5]
I`m using react with Unity-3D Game engine and i want to keep alive some routes, can i use it?

**Comment by shenjunru** [comment]
only react-dom renderer is supported

**Comment by shenjunru** [comment]
It is possible to support other react renderer.
I can expose used view instance manipulators (like `react-reconciler` config), and input by react context.
This requires the view instance can be hosted on js side.

So far, as I know `react-native` is not supported, which requires native implementation.
Ref: https://github.com/paol-imi/react-reparenting/issues/7

**Comment by weee-shinan** [comment]
I have failed to use this library in my nextjs project
